site_name: Resumen Apache2
site_url: https://framafra.github.io/resumen_Apache2/
docs_dir: 'md'
site_dir: 'docs'
repo_url: https://github.com/framafra/resumen_Apache2 #para mostrar un link al repositorio
repo_name: framafra/resumen_Apache2

nav:
    - Home: index.md
    - Instalación : inst.md
    - Directorios/Archivos de Configuración: dir.md
    - Servicio Apache2 : servicio.md
    - Directivas más importantes : directivas.md
    - Configuración mínima de un sitio : conf.md
    - Restringir acceso a una web por IP : restr.md
    - Añadir o modificar puertos de escucha : puertos.md
    - Permitir listar el contenido de un directorio : listar.md
    - Mecanismos de autentificación : mecanismos.md


theme:
    name: material
    include_search_page: false
    font:
        code: Roboto
        text: Baloo 2
    palette: 
      scheme: default
      primary: teal
      accent: green
    favicon: images/apache.png
    features:
        #- header.autohide
        - toc.follow
        - toc.integrate
        - search.suggest


extra:
    generator: false #Muestra en el pie de página que se ha realizado con Mkdocs
    social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<email-address>
    


